language: android
sudo: false
jdk:
    - oraclejdk8
before_install:
    - nvm install 12
    - node --version
    - gradle --version
install:
    - npm install -g npm
    - npm install
    - echo y | android --silent update sdk --no-ui --all --filter platform-tools,tools,build-tools-26.0.0,android-26,android-25,extra-google-m2repository,extra-android-m2repository
android:
    components:
      - tools
script:
    - npm run webpack
    - npm test
after_script:
    
